# Generated by Django 2.0.13 on 2019-05-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_reply_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='highlighted',
            field=models.TextField(default=''),
        ),
    ]
