# Generated by Django 2.0.13 on 2019-06-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='nikola.novarlic.10@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reply',
            name='email',
            field=models.EmailField(default='nikola.novarlic.10@gmail.com', max_length=254),
        ),
    ]
