# Generated by Django 2.0.13 on 2019-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20190604_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
